import React from 'react';
import {BookOpen, Compass, HelpCircle, Map, Menu, Search, Shield, X} from 'lucide-react';

export const navItems=[{id:'world',label:'Mundo',icon:Map},{id:'explore',label:'Explorar',icon:Compass},{id:'search',label:'Buscar',icon:Search},{id:'lost',label:'Estou perdido',icon:HelpCircle}];
export function Header({section,onNavigate,onSearch,onLost,onMenu}){return <header className="topbar">
  <button className="brand" onClick={()=>onNavigate('home')} aria-label="Voltar ao início"><span className="brand-mark"><Shield size={18}/></span><span><b>ATLAS</b><small>WESTEROS</small></span></button>
  <nav className="desktop-nav" aria-label="Navegação principal">{navItems.slice(0,2).map(({id,label,icon:Icon})=><button key={id} className={section===id?'active':''} onClick={()=>onNavigate(id)}><Icon size={16}/>{label}</button>)}<button onClick={onSearch}><Search size={16}/>Buscar</button></nav>
  <div className="top-actions"><button className="ghost-button lost-trigger" onClick={onLost}><HelpCircle size={16}/>Estou perdido</button><button className="icon-button mobile-only" onClick={onMenu} aria-label="Abrir menu"><Menu/></button></div>
</header>}
export function MobileMenu({section,onNavigate,onClose,onLost}){return <div className="mobile-menu" role="dialog" aria-modal="true" aria-label="Menu"><div className="mobile-menu-head"><span className="eyebrow">NAVEGAÇÃO</span><button className="icon-button" onClick={onClose} aria-label="Fechar"><X/></button></div><button className={section==='home'?'menu-row active':'menu-row'} onClick={()=>onNavigate('home')}><BookOpen/> Início</button><button className={section==='world'?'menu-row active':'menu-row'} onClick={()=>onNavigate('world')}><Map/> Mundo</button><button className={section==='explore'?'menu-row active':'menu-row'} onClick={()=>onNavigate('explore')}><Compass/> Explorar</button><button className={section==='search'?'menu-row active':'menu-row'} onClick={()=>onNavigate('search')}><Search/> Buscar</button><button className="menu-row lost" onClick={()=>{onClose();onLost()}}><HelpCircle/> Estou perdido</button></div>}
export function BottomNav({section,onNavigate,onLost}){return <nav className="bottom-nav" aria-label="Navegação móvel"><button className={section==='world'?'active':''} onClick={()=>onNavigate('world')}><Map/><span>Mundo</span></button><button className={section==='explore'?'active':''} onClick={()=>onNavigate('explore')}><Compass/><span>Explorar</span></button><button className={section==='search'?'active':''} onClick={()=>onNavigate('search')}><Search/><span>Buscar</span></button><button onClick={onLost}><HelpCircle/><span>Perdido</span></button></nav>}
